# Generated by Django 4.1.1 on 2022-12-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_alter_reservation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='operatingAirlines',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
